
import { Product, Category, Language, Currency } from '@/types';

export const EXCHANGE_RATES: Record<Currency, number> = {
  USD: 1 / 930,
  EUR: 1 / 1010, // Approximate inverse of 0.92 * 1100
  AOA: 1
};

export const CURRENCY_SYMBOLS: Record<Currency, string> = {
  USD: '$',
  EUR: '€',
  AOA: 'Kz'
};

export const TRANSLATIONS: Record<Language, any> = {
  pt: {
    header: {
      support: 'Atendimento',
      compare: 'Comparar',
      wishlist: 'Wishlist',
      cart: 'Cart',
      login: 'Entrar',
      dashboard: 'Painel',
      search_placeholder: 'O que você procura hoje?',
      search_btn: 'Buscar',
      nav: {
        home: 'Início',
        categories: 'Categorias',
        deals: 'Ofertas',
        blog: 'Blog',
        about: 'Sobre',
        contact: 'Contacto'
      }
    },
    categories: {
      informatica: 'Informática',
      escritorio: 'Escritório',
      electrodomesticos: 'Electrodomésticos',
      seguranca: 'Segurança',
      smartphones: 'Telemóveis',
      energia: 'Energia',
      'imagem-som': 'Imagem e Som',
      'jogos-consolas': 'Jogos e Consolas',
      'beleza-saude': 'Beleza e Saúde'
    },
    products: {
      'inf-001': 'MacBook Pro 14" Chip M3',
      'inf-002': 'Teclado Mecânico Logitech G915',
      'inf-003': 'Mini PC Intel NUC 13 Pro',
      'inf-004': 'Monitor LG UltraGear 27"',
      'esc-001': 'Cadeira Ergonómica Miller X',
      'esc-002': 'Impressora HP LaserJet Pro M404n',
      'esc-003': 'Secretária Elevatória Elétrica',
      'ele-001': 'Frigorífico Americano Samsung',
      'ele-002': 'Máquina de Lavar LG Vivace 9kg',
      'ele-003': 'Micro-ondas Panasonic Inverter',
      'seg-001': 'Kit Alarme Ajax Hub Plus',
      'seg-002': 'Câmara IP Exterior Reolink 4K',
      'pho-001': 'iPhone 15 Pro Max 256GB',
      'pho-002': 'Samsung Galaxy S24 Ultra',
      'pho-003': 'iPad Pro 12.9" M2 512GB',
      'ene-001': 'UPS APC Back-UPS 700VA',
      'ene-002': 'Painel Solar 450W',
      'ims-001': 'Smart TV Samsung 65" QLED 4K',
      'ims-002': 'Soundbar Sony HT-S400',
      'jog-001': 'PlayStation 5 Slim 1TB',
      'jog-002': 'Nintendo Switch OLED',
      'bel-001': 'Secador Dyson Supersonic',
      'bel-002': 'Termómetro Digital Braun'
    },
    shop: {
      viewing: 'Visualizando',
      items: 'itens',
      sort_by: 'Ordenar por',
      recent: 'Mais Recentes',
      price_asc: 'Preço: Menor ao Maior',
      price_desc: 'Preço: Maior ao Menor',
      best_rated: 'Melhores Avaliações',
      price_max: 'Preço Máximo',
      add_to_cart: 'Adicionar',
      no_results: 'Sem Resultados',
      stock: 'Stock',
      no_stock: 'Sem Stock'
    },
    footer: {
      free_shipping: 'Envio Grátis',
      free_shipping_desc: 'Compras acima de $100',
      secure_pay: 'Compra Segura',
      secure_pay_desc: 'Pagamentos protegidos',
      trust: 'Confiança Total',
      trust_desc: 'Garantia de satisfação',
      support_24: 'Suporte 24/7',
      support_24_desc: 'Fale connosco',
      products: 'Produtos',
      company: 'A Empresa',
      social: 'Redes Sociais',
      newsletter: 'Novidades',
      email_placeholder: 'Seu melhor e-mail',
      rights: 'Todos os Direitos Reservados'
    },
    cart: {
      title: 'Carrinho de Compras',
      empty: 'Seu Carrinho está Vazio',
      start_shop: 'Começar a Comprar',
      proforma: 'Gerar Fatura Proforma',
      remove: 'Remover',
      image: 'Imagem',
      product: 'Produto',
      price: 'Preço',
      qty: 'Qtd',
      total: 'Total',
      summary: 'Totais',
      subtotal: 'Subtotal',
      shipping: 'Envio',
      free: 'Grátis',
      final_total: 'Total Final',
      checkout: 'Finalizar Compra'
    },
    admin: {
      sidebar: {
        dashboard: 'Painel Principal',
        home_mgmt: 'Gestão da Home',
        new_sale: 'Nova Venda (POS)',
        orders: 'Pedidos',
        products: 'Produtos',
        inventory: 'Inventário',
        reports: 'Relatórios',
        marketplaces: 'Marketplaces',
        customers: 'Clientes',
        marketing: 'Marketing',
        settings: 'Definições',
        exit: 'Sair do Painel',
        logout: 'Terminar Sessão'
      },
      dashboard: {
        revenue: 'Receita Total',
        orders_count: 'Pedidos',
        active_products: 'Produtos Ativos',
        critical_stock: 'Stock Crítico',
        rupture_risk: 'Risco de Ruptura',
        pending_orders: 'Pedidos Pendentes'
      },
      inventory: {
        title: 'Controlo de Stock',
        current: 'Stock Atual',
        history: 'Histórico',
        search_placeholder: 'Pesquisar por nome, SKU...',
        table_product: 'Produto',
        table_sync: 'Sincronização',
        table_qty: 'Quantidade',
        table_actions: 'Ações',
        adjust: 'Ajustar'
      },
      pos: {
        title: 'Terminal de Faturamento',
        search_products: 'Buscar produtos...',
        cart: 'CARRINHO',
        identify_customer: 'Identificar Cliente...',
        tax_base: 'Base Tributável',
        tax_iva: 'IVA (14% Incluso)',
        total_to_pay: 'Total a Pagar',
        received: 'Valor Recebido...',
        change: 'Troco / Saldo Gerado',
        btn_proforma: 'PROFORMA',
        btn_recibo: 'F. RECIBO',
        btn_finish: 'FINALIZAR VENDA'
      }
    }
  },
  en: {
    header: {
      support: 'Customer Support',
      compare: 'Compare',
      wishlist: 'Wishlist',
      cart: 'Cart',
      login: 'Sign In',
      dashboard: 'Panel',
      search_placeholder: 'What are you looking for today?',
      search_btn: 'Search',
      nav: {
        home: 'Home',
        categories: 'Categories',
        deals: 'Hot Deals',
        blog: 'Blog',
        about: 'About',
        contact: 'Contact'
      }
    },
    categories: {
      informatica: 'Computing',
      escritorio: 'Office',
      electrodomesticos: 'Appliances',
      seguranca: 'Security',
      smartphones: 'Mobile Phones',
      energia: 'Energy',
      'imagem-som': 'TV & Audio',
      'jogos-consolas': 'Gaming & Sports',
      'beleza-saude': 'Beauty & Health'
    },
    products: {
      'inf-001': 'MacBook Pro 14" M3 Chip',
      'inf-002': 'Logitech G915 Mechanical Keyboard',
      'inf-003': 'Intel NUC 13 Pro Mini PC',
      'inf-004': 'LG UltraGear 27" Monitor',
      'esc-001': 'Miller X Ergonomic Chair',
      'esc-002': 'HP LaserJet Pro M404n',
      'esc-003': 'Electric Standing Desk',
      'ele-001': 'Samsung Side-by-Side Fridge',
      'ele-002': 'LG Vivace 9kg Washing Machine',
      'ele-003': 'Panasonic Inverter Microwave',
      'seg-001': 'Ajax Hub Plus Alarm Kit',
      'seg-002': 'Reolink 4K Outdoor IP Camera',
      'pho-001': 'iPhone 15 Pro Max 256GB',
      'pho-002': 'Samsung Galaxy S24 Ultra',
      'pho-003': 'iPad Pro 12.9" M2 512GB',
      'ene-001': 'APC Back-UPS 700VA',
      'ene-002': '450W Solar Panel',
      'ims-001': 'Samsung 65" QLED 4K TV',
      'ims-002': 'Sony HT-S400 Soundbar',
      'jog-001': 'PlayStation 5 Slim 1TB',
      'jog-002': 'Nintendo Switch OLED',
      'bel-001': 'Dyson Supersonic Hair Dryer',
      'bel-002': 'Braun Digital Thermometer'
    },
    shop: {
      viewing: 'Viewing',
      items: 'items',
      sort_by: 'Sort by',
      recent: 'Most Recent',
      price_asc: 'Price: Low to High',
      price_desc: 'Price: High to Low',
      best_rated: 'Best Rated',
      price_max: 'Max Price',
      add_to_cart: 'Add',
      no_results: 'No Results Found',
      stock: 'Stock',
      no_stock: 'Out of Stock'
    },
    footer: {
      free_shipping: 'Free Shipping',
      free_shipping_desc: 'Orders over $100',
      secure_pay: 'Secure Purchase',
      secure_pay_desc: 'Protected payments',
      trust: 'Total Trust',
      trust_desc: 'Satisfaction guarantee',
      support_24: '24/7 Support',
      support_24_desc: 'Contact us anytime',
      products: 'Products',
      company: 'Company',
      social: 'Social Media',
      newsletter: 'Newsletter',
      email_placeholder: 'Your best email',
      rights: 'All Rights Reserved'
    },
    cart: {
      title: 'Shopping Cart',
      empty: 'Your Cart is Empty',
      start_shop: 'Start Shopping',
      proforma: 'Generate Proforma',
      remove: 'Remove',
      image: 'Image',
      product: 'Product',
      price: 'Price',
      qty: 'Qty',
      total: 'Total',
      summary: 'Summary',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      free: 'Free',
      final_total: 'Final Total',
      checkout: 'Checkout'
    },
    admin: {
      sidebar: {
        dashboard: 'Dashboard',
        home_mgmt: 'Home Management',
        new_sale: 'New Sale (POS)',
        orders: 'Orders',
        products: 'Products',
        inventory: 'Inventory',
        reports: 'Reports',
        marketplaces: 'Marketplaces',
        customers: 'Customers',
        marketing: 'Marketing',
        settings: 'Settings',
        exit: 'Exit Admin',
        logout: 'Logout'
      },
      dashboard: {
        revenue: 'Total Revenue',
        orders_count: 'Orders',
        active_products: 'Active Products',
        critical_stock: 'Critical Stock',
        rupture_risk: 'Stock Rupture Risk',
        pending_orders: 'Pending Orders'
      },
      inventory: {
        title: 'Stock Control',
        current: 'Current Stock',
        history: 'History',
        search_placeholder: 'Search name, SKU...',
        table_product: 'Product',
        table_sync: 'Sync',
        table_qty: 'Quantity',
        table_actions: 'Actions',
        adjust: 'Adjust'
      },
      pos: {
        title: 'Sales Terminal',
        search_products: 'Search products...',
        cart: 'CART',
        identify_customer: 'Identify Customer...',
        tax_base: 'Tax Base',
        tax_iva: 'VAT (14% Included)',
        total_to_pay: 'Total to Pay',
        received: 'Amount Received...',
        change: 'Change / Balance',
        btn_proforma: 'PROFORMA',
        btn_recibo: 'RECEIPT',
        btn_finish: 'FINISH SALE'
      }
    }
  },
  es: {
    header: {
      support: 'Atención',
      compare: 'Comparar',
      wishlist: 'Favoritos',
      cart: 'Carrito',
      login: 'Acceder',
      dashboard: 'Panel',
      search_placeholder: '¿Qué estás buscando hoy?',
      search_btn: 'Buscar',
      nav: {
        home: 'Inicio',
        categories: 'Categorías',
        deals: 'Ofertas',
        blog: 'Blog',
        about: 'Nosotros',
        contact: 'Contacto'
      }
    },
    categories: {
      informatica: 'Informática',
      escritorio: 'Oficina',
      electrodomesticos: 'Electrodomésticos',
      seguranca: 'Seguridad',
      smartphones: 'Móviles',
      energia: 'Energía',
      'imagem-som': 'Imagen y Sonido',
      'jogos-consolas': 'Juegos y Consolas',
      'beleza-saude': 'Belleza y Salud'
    },
    products: {
      'inf-001': 'MacBook Pro 14" Chip M3',
      'inf-002': 'Teclado Mecânico Logitech G915',
      'inf-003': 'Mini PC Intel NUC 13 Pro',
      'inf-004': 'Monitor LG UltraGear 27"',
      'esc-001': 'Silla Ergonómica Miller X',
      'esc-002': 'HP LaserJet Pro M404n',
      'esc-003': 'Escritorio Elevable Eléctrico',
      'ele-001': 'Frigorífico Americano Samsung',
      'ele-002': 'Lavadora LG Vivace 9kg',
      'ele-003': 'Microondas Panasonic Inverter',
      'seg-001': 'Kit Alarma Ajax Hub Plus',
      'seg-002': 'Cámara IP Exterior Reolink 4K',
      'pho-001': 'iPhone 15 Pro Max 256GB',
      'pho-002': 'Samsung Galaxy S24 Ultra',
      'pho-003': 'iPad Pro 12.9" M2 512GB',
      'ene-001': 'SAI APC Back-UPS 700VA',
      'ene-002': 'Panel Solar 450W',
      'ims-001': 'Smart TV Samsung 65" QLED 4K',
      'ims-002': 'Barra de Sonido Sony HT-S400',
      'jog-001': 'PlayStation 5 Slim 1TB',
      'jog-002': 'Nintendo Switch OLED',
      'bel-001': 'Secador Dyson Supersonic',
      'bel-002': 'Termómetro Digital Braun'
    },
    shop: {
      viewing: 'Viendo',
      items: 'artículos',
      sort_by: 'Ordenar por',
      recent: 'Más Recientes',
      price_asc: 'Precio: Menor a Mayor',
      price_desc: 'Precio: Mayor a Menor',
      best_rated: 'Mejor Valorados',
      price_max: 'Precio Máximo',
      add_to_cart: 'Añadir',
      no_results: 'Sin Resultados',
      stock: 'Existencias',
      no_stock: 'Sin Stock'
    },
    footer: {
      free_shipping: 'Envío Gratis',
      free_shipping_desc: 'Compras sobre $100',
      secure_pay: 'Compra Segura',
      secure_pay_desc: 'Pagos protegidos',
      trust: 'Confianza Total',
      trust_desc: 'Garantia de satisfacción',
      support_24: 'Soporte 24/7',
      support_24_desc: 'Habla con nosotros',
      products: 'Productos',
      company: 'La Empresa',
      social: 'Redes Sociais',
      newsletter: 'Novedades',
      email_placeholder: 'Tu mejor email',
      rights: 'Todos los Derechos Reservados'
    },
    cart: {
      title: 'Carrito de Compras',
      empty: 'Tu Carrito está Vacío',
      start_shop: 'Empezar a Comprar',
      proforma: 'Generar Proforma',
      remove: 'Eliminar',
      image: 'Imagen',
      product: 'Producto',
      price: 'Precio',
      qty: 'Cant',
      total: 'Total',
      summary: 'Resumen',
      subtotal: 'Subtotal',
      shipping: 'Envío',
      free: 'Gratis',
      final_total: 'Total Final',
      checkout: 'Finalizar Pedido'
    },
    admin: {
      sidebar: {
        dashboard: 'Panel Principal',
        home_mgmt: 'Gestión de Inicio',
        new_sale: 'Nueva Venta (POS)',
        orders: 'Pedidos',
        products: 'Productos',
        inventory: 'Inventario',
        reports: 'Reportes',
        marketplaces: 'Marketplaces',
        customers: 'Clientes',
        marketing: 'Marketing',
        settings: 'Ajustes',
        exit: 'Salir del Panel',
        logout: 'Cerrar Sesión'
      },
      dashboard: {
        revenue: 'Ingresos Totales',
        orders_count: 'Pedidos',
        active_products: 'Productos Activos',
        critical_stock: 'Stock Crítico',
        rupture_risk: 'Riesgo de Ruptura',
        pending_orders: 'Pedidos Pendentes'
      },
      inventory: {
        title: 'Control de Stock',
        current: 'Stock Actual',
        history: 'Historial',
        search_placeholder: 'Buscar nombre, SKU...',
        table_product: 'Producto',
        table_sync: 'Sincronización',
        table_qty: 'Cantidad',
        table_actions: 'Acciones',
        adjust: 'Ajustar'
      },
      pos: {
        title: 'Terminal de Ventas',
        search_products: 'Buscar productos...',
        cart: 'CARRITO',
        identify_customer: 'Identificar Cliente...',
        tax_base: 'Base Imponible',
        tax_iva: 'IVA (14% Incluido)',
        total_to_pay: 'Total a Pagar',
        received: 'Monto Recibido...',
        change: 'Cambio / Saldo',
        btn_proforma: 'PROFORMA',
        btn_recibo: 'FACTURA',
        btn_finish: 'FINALIZAR VENTA'
      }
    }
  },
  fr: {
    header: {
      support: 'Assistance',
      compare: 'Comparer',
      wishlist: 'Favoris',
      cart: 'Panier',
      login: 'Connexion',
      dashboard: 'Tableau',
      search_placeholder: 'Que cherchez-vous aujourd\'hui ?',
      search_btn: 'Chercher',
      nav: {
        home: 'Accueil',
        categories: 'Catégories',
        deals: 'Offres',
        blog: 'Blog',
        about: 'À Propos',
        contact: 'Contact'
      }
    },
    categories: {
      informatica: 'Informatique',
      escritorio: 'Bureau',
      electrodomesticos: 'Électroménager',
      seguranca: 'Sécurité',
      smartphones: 'Téléphones',
      energia: 'Énergie',
      'imagem-som': 'Image & Son',
      'jogos-consolas': 'Jeux & Sport',
      'beleza-saude': 'Beauté & Santé'
    },
    products: {
      'inf-001': 'MacBook Pro 14" Puce M3',
      'inf-002': 'Clavier Mécanique Logitech G915',
      'inf-003': 'Mini PC Intel NUC 13 Pro',
      'inf-004': 'Ecran LG UltraGear 27"',
      'esc-001': 'Chaise Ergonomique Miller X',
      'esc-002': 'HP LaserJet Pro M404n',
      'esc-003': 'Bureau Assis-Debout Électrique',
      'ele-001': 'Réfrigérateur Samsung Side-by-Side',
      'ele-002': 'Lave-linge LG Vivace 9kg',
      'ele-003': 'Micro-ondes Panasonic Inverter',
      'seg-001': 'Kit Alarme Ajax Hub Plus',
      'seg-002': 'Caméra IP Extérieure Reolink 4K',
      'pho-001': 'iPhone 15 Pro Max 256GB',
      'pho-002': 'Samsung Galaxy S24 Ultra',
      'pho-003': 'iPad Pro 12.9" M2 512GB',
      'ene-001': 'Onduleur APC Back-UPS 700VA',
      'ene-002': 'Panneau Solaire 450W',
      'ims-001': 'Smart TV Samsung 65" QLED 4K',
      'ims-002': 'Barre de Son Sony HT-S400',
      'jog-001': 'PlayStation 5 Slim 1TB',
      'jog-002': 'Nintendo Switch OLED',
      'bel-001': 'Sèche-cheveux Dyson Supersonic',
      'bel-002': 'Thermomètre Digital Braun'
    },
    shop: {
      viewing: 'Affichage',
      items: 'articles',
      sort_by: 'Trier par',
      recent: 'Plus récents',
      price_asc: 'Prix : Croissant',
      price_desc: 'Prix : Décroissant',
      best_rated: 'Mieux notés',
      price_max: 'Prix Maximum',
      add_to_cart: 'Ajouter',
      no_results: 'Aucun Résultat',
      stock: 'Stock',
      no_stock: 'Épuisé'
    },
    footer: {
      free_shipping: 'Livraison Gratuite',
      free_shipping_desc: 'Dès 100$',
      secure_pay: 'Achat Sécurisé',
      secure_pay_desc: 'Paiements protégés',
      trust: 'Confiance Totale',
      trust_desc: 'Garantie satisfaction',
      support_24: 'Support 24/7',
      support_24_desc: 'Contactez-nous',
      products: 'Produits',
      company: 'L\'Entreprise',
      social: 'Réseaux Sociaux',
      newsletter: 'Nouveautés',
      email_placeholder: 'Votre meilleur email',
      rights: 'Tous Droits Réservés'
    },
    cart: {
      title: 'Panier d\'Achat',
      empty: 'Votre Panier est Vide',
      start_shop: 'Commencer l\'Achat',
      proforma: 'Générer Proforma',
      remove: 'Supprimer',
      image: 'Image',
      product: 'Produit',
      price: 'Prix',
      qty: 'Qté',
      total: 'Total',
      summary: 'Sommaire',
      subtotal: 'Sous-total',
      shipping: 'Livraison',
      free: 'Gratuit',
      final_total: 'Total Final',
      checkout: 'Commander'
    },
    admin: {
      sidebar: {
        dashboard: 'Tableau de Bord',
        home_mgmt: 'Gestion Accueil',
        new_sale: 'Nouvelle Vente (POS)',
        orders: 'Commandes',
        products: 'Produits',
        inventory: 'Inventaire',
        reports: 'Rapports',
        marketplaces: 'Places de Marché',
        customers: 'Clients',
        marketing: 'Marketing',
        settings: 'Paramètres',
        exit: 'Quitter Admin',
        logout: 'Déconnexion'
      },
      dashboard: {
        revenue: 'Revenu Total',
        orders_count: 'Commandes',
        active_products: 'Produits Actifs',
        critical_stock: 'Stock Critique',
        rupture_risk: 'Risque de Rupture',
        pending_orders: 'Commandes en Attente'
      },
      inventory: {
        title: 'Controle de Stock',
        current: 'Stock Actual',
        history: 'Historique',
        search_placeholder: 'Rechercher nom, SKU...',
        table_product: 'Produit',
        table_sync: 'Sync',
        table_qty: 'Quantité',
        table_actions: 'Actions',
        adjust: 'Ajuster'
      },
      pos: {
        title: 'Terminal de Vente',
        search_products: 'Rechercher produits...',
        cart: 'PANIER',
        identify_customer: 'Identifier Client...',
        tax_base: 'Base Taxable',
        tax_iva: 'TVA (14% Inclus)',
        total_to_pay: 'Total à Payer',
        received: 'Montant Reçu...',
        change: 'Monnaie / Solde',
        btn_proforma: 'PROFORMA',
        btn_recibo: 'FACTURE',
        btn_finish: 'TERMINER LA VENTE'
      }
    }
  }
};

export interface SubCategory {
  id: string;
  name: string;
  items?: string[];
}

export interface EnhancedCategory extends Category {
  subCategories?: SubCategory[];
  iconName: string;
}

export const ENHANCED_CATEGORIES: EnhancedCategory[] = [
  {
    id: '1',
    name: 'Informática',
    slug: 'informatica',
    iconName: 'Monitor',
    subCategories: [
      { id: 's1-1', name: 'Computadores Desktops', items: ['StandAlone', 'All-In-One', 'Mini Pc', 'Monitor + PC'] },
      { id: 's1-2', name: 'Computadores Portáteis', items: ['Portáteis Casa e Escritório', 'Gaming Laptops', 'Workstations'] },
      { id: 's1-3', name: 'Acessórios e Periféricos', items: ['Ratos e Teclados', 'Webcams', 'Auscultadores', 'Colunas de Som'] },
      { id: 's1-4', name: 'Armazenamento', items: ['Discos Externos HDD', 'Discos Internos SSD', 'Pen Drives', 'Cartões de Memória'] },
      { id: 's1-5', name: 'Impressão e Imagem', items: ['Impressoras Laser', 'Multifunções', 'Toners e Tinteiros', 'Scanners'] },
      { id: 's1-6', name: 'Licenças de Software', items: ['Windows 11 Pro', 'Office 2024 ESD', 'Antivírus', 'Cloud & Servidores', 'Outras Licenças'] },
    ]
  },
  {
    id: '2',
    name: 'Escritório',
    slug: 'escritorio',
    iconName: 'Briefcase',
    subCategories: [
      { id: 's2-1', name: 'Mobiliário', items: ['Cadeiras de Escritório', 'Secretárias', 'Armários e Estantes'] },
      { id: 's2-2', name: 'Papelaria', items: ['Papel A4', 'Envelopes', 'Pastas de Arquivo', 'Agendas'] },
      { id: 's2-3', name: 'Escrita e Correção', items: ['Canetas', 'Lápis', 'Marcadores', 'Corretores'] },
      { id: 's2-4', name: 'Máquinas de Escritório', items: ['Calculadoras', 'Destruidoras de Papel', 'Plastificadoras'] },
    ]
  },
  {
    id: '3',
    name: 'Electrodomésticos',
    slug: 'electrodomesticos',
    iconName: 'ChefHat',
    subCategories: [
      { id: 's3-1', name: 'Cozinha', items: ['Frigoríficos', 'Fogões', 'Micro-ondas', 'Máquinas de Café', 'Torradeiras'] },
      { id: 's3-2', name: 'Lavandaria', items: ['Máquinas de Lavar Roupa', 'Máquinas de Secar', 'Ferros de Engomar'] },
      { id: 's3-3', name: 'Climatização', items: ['Ar Condicionado', 'Ventoinhas', 'Aquecedores'] },
    ]
  },
  {
    id: '4',
    name: 'Segurança',
    slug: 'seguranca',
    iconName: 'Shield',
    subCategories: [
      { id: 's4-1', name: 'Vigilância (CCTV)', items: ['Câmaras IP', 'Gravadores NVR/DVR', 'Kits Completos'] },
      { id: 's4-2', name: 'Alarmes', items: ['Central de Alarme', 'Sensores de Movimento', 'Sirenes'] },
      { id: 's4-3', name: 'Controlo de Acessos', items: ['Fechaduras Eletrónicas', 'Leitores Biométricos', 'Intercomunicadores'] },
      { id: 's4-4', name: 'Proteção Contra Fogo', items: ['Detetores de Fumo', 'Extintores'] },
    ]
  },
  {
    id: '5',
    name: 'Telemóveis',
    slug: 'smartphones',
    iconName: 'Smartphone',
    subCategories: [
      { id: 's5-1', name: 'Smartphones', items: ['iPhone (iOS)', 'Samsung (Android)', 'Xiaomi', 'Oppo'] },
      { id: 's5-2', name: 'Acessórios Mobile', items: ['Capas e Proteções', 'Películas de Vidro', 'Carregadores', 'Powerbanks'] },
      { id: 's5-3', name: 'Smartwatches', items: ['Apple Watch', 'Galaxy Watch', 'Smartbands'] },
      { id: 's5-4', name: 'Áudio Bluetooth', items: ['AirPods', 'Galaxy Buds', 'Auscultadores Wireless'] },
    ]
  },
  {
    id: '7',
    name: 'Energia',
    slug: 'energia',
    iconName: 'Zap',
    subCategories: [
      { id: 's7-1', name: 'Energia Solar', items: ['Painéis Solares', 'Inversores', 'Baterias de Lítio', 'Controladores de Carga'] },
      { id: 's7-2', name: 'Proteção de Energia', items: ['UPS / No-breaks', 'Estabilizadores', 'Extensões com Filtro'] }
    ]
  },
  {
    id: '8',
    name: 'Imagem e Som',
    slug: 'imagem-som',
    iconName: 'Tv',
    subCategories: [
      { id: 's8-1', name: 'Televisores', items: ['Smart TVs 4K', 'OLED/QLED', 'Suportes de TV'] },
      { id: 's8-2', name: 'Áudio Profissional', items: ['Soundbars', 'Home Cinema', 'Colunas Bluetooth', 'Amplificadores'] }
    ]
  },
  {
    id: '9',
    name: 'Jogos, Consolas e Desporto',
    slug: 'jogos-consolas',
    iconName: 'Gamepad2',
    subCategories: [
      { id: 's9-1', name: 'Consolas', items: ['PlayStation 5', 'Xbox Series X/S', 'Nintendo Switch'] },
      { id: 's9-2', name: 'Acessórios Gaming', items: ['Comandos', 'Headsets', 'Cadeiras Gaming', 'Volantes'] }
    ]
  },
  {
    id: '6',
    name: 'Beleza e Saúde',
    slug: 'beleza-saude',
    iconName: 'User',
    subCategories: [
      { id: 's6-1', name: 'Cuidado Pessoal', items: ['Secadores de Cabelo', 'Máquinas de Barbear', 'Escovas Elétricas', 'Pranchas de Cabelo'] },
      { id: 's6-2', name: 'Perfumes', items: ['Fragrâncias Masculinas', 'Fragrâncias Femininas', 'Kits de Perfume'] },
      { id: 's6-3', name: 'Saúde e Bem Estar', items: ['Medidores de Tensão', 'Termómetros', 'Massajadores', 'Purificadores de Ar'] },
    ]
  },
];

export const MOCK_PRODUCTS: Product[] = [
  // SOFTWARE & LICENÇAS
  {
    id: 'soft-001',
    name: 'SW MS Office Casa & Negócio 2024 - ESD',
    description: 'Licença digital Vitalícia para 1 PC ou Mac. Inclui Word, Excel, PowerPoint e Outlook. A solução definitiva para profissionais e famílias que necessitam das ferramentas clássicas da Microsoft com o pagamento único. Aproveite os novos recursos de colaboração e produtividade.',
    price: 252812.16,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Office 2024 ESD',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1633419461186-7d40a38105ec?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80'],
    stock: 50,
    minStock: 5,
    variations: [],
    rating: 4.9,
    reviewsCount: 15,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-002',
    name: 'SW MS Windows 11 Pro ESD Digital License',
    description: 'Chave de ativação digital para Windows 11 Pro. Envio imediato via e-mail. Maximize a sua produtividade diária com a interface renovada e as ferramentas corporativas exclusivas da versão Pro, como BitLocker, Hyper-V e Remote Desktop.',
    price: 242269.12,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Windows 11 Pro',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1629654297299-c8506221eca9?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=800&q=80'],
    stock: 100,
    minStock: 10,
    variations: [],
    rating: 4.8,
    reviewsCount: 22,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-003',
    name: 'SW Antivirus Kaspersky Standard - 5 Dispositivos',
    description: 'Proteção essencial para os seus dispositivos contra vírus e malware. Licença de 1 ano válida para até 5 dispositivos. Navegue, compre e faça operações bancárias de forma segura. Inclui proteção em tempo real e anti-phishing.',
    price: 37353.29,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Antivírus',
    brand: 'Kaspersky',
    images: ['https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&w=800&q=80'],
    stock: 200,
    minStock: 20,
    variations: [],
    rating: 4.7,
    reviewsCount: 35,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-004',
    name: 'SW Antivirus Kaspersky Plus - 3 Dispositivos',
    description: 'Segurança cibernética avançada com VPN e gestor de passwords. Licença de 1 ano para 3 dispositivos. Defenda-se contra ransomware, otimize o desempenho do seu PC e garanta a segurança da sua identidade online com encriptação premium.',
    price: 27192.18,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Antivírus',
    brand: 'Kaspersky',
    images: ['https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80'],
    stock: 150,
    minStock: 15,
    variations: [],
    rating: 4.8,
    reviewsCount: 28,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-005',
    name: 'SW Antivirus Kaspersky Premium - 5 Dispositivos',
    description: 'Proteção total com suporte técnico prioritário, VPN ilimitada e proteção de identidade. Licença de 1 ano para até 5 dispositivos. O expoente máximo da segurança pessoal para famílias modernas e indivíduos preocupados com a privacidade.',
    price: 36864.14,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Antivírus',
    brand: 'Kaspersky',
    images: ['https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80'],
    stock: 80,
    minStock: 10,
    variations: [],
    rating: 4.9,
    reviewsCount: 12,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-006',
    name: 'SW Antivirus Norton 360 Deluxe - 5 Dispositivos',
    description: 'Segurança completa para Windows, macOS, iOS e Android. Licença de 1 ano. Beneficie de Secure VPN, backup avançado na cloud, gestor de passwords integrados e Dark Web Monitoring. Uma solução tudo-em-um.',
    price: 27935.04,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Antivírus',
    brand: 'Norton',
    images: ['https://images.unsplash.com/photo-1555099962-4199c345e5dd?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?auto=format&fit=crop&w=800&q=80'],
    stock: 45,
    minStock: 5,
    variations: [],
    rating: 4.8,
    reviewsCount: 19,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-calc-001',
    name: 'Microsoft Office 2024 Professional Plus 1PC',
    description: 'Licença Definitiva para profissionais. Inclui todas as aplicações clássicas do Office (Word, Excel, PowerPoint, Outlook, Publisher e Access). Uma compra única revolucionária com acesso constante às ferramentas essenciais do escritório sem subscrição mensal.',
    price: 245000.00,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Office 2024 ESD',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1633419461186-7d40a38105ec?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80'],
    stock: 10,
    minStock: 2,
    variations: [],
    rating: 5.0,
    reviewsCount: 5,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-ms-001',
    name: 'Windows Server 2025 Standard - 16 Core',
    description: 'Licença para servidores modernos. Performance e segurança de nível empresarial. Gere e controle infraestruturas de rede de grande escala, com capacidades aprimoradas para nuvem híbrida e contentores, otimizada para o centro de dados de amanhã.',
    price: 2319866.81,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Cloud & Servidores',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80'],
    stock: 5,
    minStock: 1,
    variations: [],
    rating: 4.9,
    reviewsCount: 3,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-ms-002',
    name: 'Copilot for Microsoft 365 - Anual',
    description: 'Aumente drasticamente a inteligência da sua equipa com a subscrição anual do Microsoft Copilot. Inteligência Artificial integrada diretamente nas suas aplicações de trabalho da Microsoft para escrever, desenhar, calcular e organizar.',
    price: 483676.92,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Cloud & Servidores',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1661956602868-6ae368943878?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1682687982501-1e58f8147d3d?auto=format&fit=crop&w=800&q=80'],
    stock: 100,
    minStock: 10,
    variations: [],
    rating: 5.0,
    reviewsCount: 8,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-ms-003',
    name: 'Microsoft SQL Server 2022 Standard',
    description: 'Gestão de bases de dados relacional líder de mercado. Suporte a big data. Oferece escalabilidade incrível, inteligência com análise de dados e segurança reforçada para empresas de médio porte que gerem dados essenciais de negócio online.',
    price: 2352601.24,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Cloud & Servidores',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80'],
    stock: 3,
    minStock: 1,
    variations: [],
    rating: 4.8,
    reviewsCount: 4,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // DESKTOPS
  {
    id: 'desk-001',
    name: 'Computador Lenovo H505S AMD-E2-1800APU',
    description: 'Computador Lenovo H505S. Equipado com AMD E2-1800 1.7GHz, 4GB RAM e disco HDD 500GB. Conta com gráfica dedicada Radeon HD 7030. Ideal para uso em escritório, recepções e navegação doméstica básica.',
    price: 734020.00,
    category: 'Informática',
    subCategory: 'Computadores Desktops',
    specificItem: 'Computadores Desktop',
    brand: 'Lenovo',
    images: ['https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=800&q=80'],
    stock: 10,
    minStock: 2,
    variations: [],
    rating: 4.2,
    reviewsCount: 5,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'desk-002',
    name: 'Mini PC Blackview MP200 Alder Lake i5-12450H',
    description: 'Mini PC Blackview MP200. Com processador Intel Alder Lake i5-12450H, 16GB RAM e SSD M.2 de 512GB, oferecendo desempenho estrondoso num formato ultra compacto. Perfeito para pequenos escritórios, estúdios ou secretárias com pouco espaço.',
    price: 397233.00,
    category: 'Informática',
    subCategory: 'Desktops',
    specificItem: 'Computadores Desktop',
    brand: 'Blackview',
    images: ['https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80'],
    stock: 15,
    minStock: 2,
    variations: [],
    rating: 4.8,
    reviewsCount: 12,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'desk-003',
    name: 'HP ProDesk 400 G7 i3-10100',
    description: 'HP ProDesk 400 G7 microtower. Intel Core i3-10100, 8GB DDR4 RAM e SSD super rápido de 256GB NVMe. Uma máquina confiável, construída para durar longos anos nas tarefas de negócios intermédias do dia-a-dia.',
    price: 806550.00,
    category: 'Informática',
    subCategory: 'Computadores Desktops',
    specificItem: 'Computadores Desktop',
    brand: 'HP',
    images: ['https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80'],
    stock: 8,
    minStock: 1,
    variations: [],
    rating: 4.5,
    reviewsCount: 8,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'desk-004',
    name: 'HP Pro Tower 400 G9 MT i9-13500',
    description: 'HP Pro Tower 400 G9 MT super robusto. Processador potente Intel Core i9-13500 para análise de dados pesados e renderização multi-tarefa. Combinado com 8GB RAM expansível e SSD NVMe de 512GB com Windows 11 Pro nativo.',
    price: 1042552.94,
    category: 'Informática',
    subCategory: 'Computadores Desktops',
    specificItem: 'Computadores Desktop',
    brand: 'HP',
    images: ['https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=800&q=80'],
    stock: 12,
    minStock: 2,
    variations: [],
    rating: 4.9,
    reviewsCount: 15,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'desk-005',
    name: 'Dell Optiplex 7020 MT i5-12500',
    description: 'Dell Optiplex 7020 MT de nível profissional. Intel Core i5-12500, com 16GB de RAM de alta frequência, SSD de 512GB e Ubuntu Linux pré-instalado. Uma workstation clássica conhecida pela sua durabilidade e eficiência térmica imbatível.',
    price: 883500.00,
    category: 'Informática',
    subCategory: 'Computadores Desktops',
    specificItem: 'Computadores Desktop',
    brand: 'Dell',
    images: ['https://images.unsplash.com/photo-1587202372744-b0a1caadeed5?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=800&q=80'],
    stock: 5,
    minStock: 1,
    variations: [],
    rating: 4.7,
    reviewsCount: 6,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // PORTÁTEIS
  {
    id: 'lap-001',
    name: 'HP OmniBook 5 Flip x360 i7-150U',
    description: 'HP OmniBook 5 Flip x360 conversível premium. Intel Core i7-150U acompanhado por 16GB RAM e SSD de 1TB. Ecrã 14 Polegadas Touch WUXGA para versatilidade completa entre tablet e portátil focado em produtividade.',
    price: 1354723.32,
    category: 'Informática',
    subCategory: 'Portáteis',
    specificItem: 'Notebooks',
    brand: 'HP',
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1504707748692-419802cf939d?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80'],
    stock: 4,
    minStock: 1,
    variations: [],
    rating: 5.0,
    reviewsCount: 10,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'lap-002',
    name: 'HP 250R G10 15.6" U5-120U',
    description: 'HP 250R G10 corporativo elegante e fiável. Ecrã de 15.6 polegadas. Alimentado pelo avançado Intel Core i5-120U, 8GB RAM e SSD 512GB. Vem com Windows 11 Pro para máxima integração nas redes corporativas.',
    price: 1376022.50,
    category: 'Informática',
    subCategory: 'Computadores Portáteis',
    specificItem: 'Notebooks',
    brand: 'HP',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1531297172867-21444458532f?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80'],
    stock: 12,
    minStock: 2,
    variations: [],
    rating: 4.6,
    reviewsCount: 22,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'lap-003',
    name: 'HP ProBook 440 G11 u5-225U',
    description: 'Portátil empresarial HP ProBook 440 G11 moderno com um belo acabamento prateado. O processador Intel Core u5-225U com 16GB RAM e um vasto SSD de 512GB resulta num sistema responsivo perfeito para profissionais sempre em viagem.',
    price: 1179040.25,
    category: 'Informática',
    subCategory: 'Computadores Portáteis',
    specificItem: 'Laptops Profissionais',
    brand: 'HP',
    images: ['https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80'],
    stock: 6,
    minStock: 1,
    variations: [],
    rating: 4.8,
    reviewsCount: 9,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // OUTROS PRODUTOS ESCRITÓRIO
  {
    id: 'esc-001',
    name: 'Cadeira Ergonómica Miller X',
    description: 'Cadeira Ergonómica Miller X de elevado padrão. Design avançado com apoio lombar regulável e encosto de cabeça ajustável. A rede respirável mantém a temperatura fresca durante longas horas no escritório, suportando até 150Kg de peso.',
    price: 1200000.00,
    category: 'Escritório',
    subCategory: 'Mobiliário',
    specificItem: 'Cadeiras de Escritório',
    brand: 'Nexus',
    images: ['https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1595514535195-8cbfaa6b8400?auto=format&fit=crop&w=800&q=80'],
    stock: 5,
    minStock: 1,
    variations: [],
    rating: 5.0,
    reviewsCount: 32,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // ELECTRODOMÉSTICOS
  {
    id: 'ele-001',
    name: 'Frigorífico Samsung Side-by-Side 647L',
    description: 'Frigorífico inteligente Samsung Side-by-Side Inox grandioso. Enorme capacidade de 647 Litros para grandes famílias. Sistema All-around Cooling, máquina de água e gelo integrada, dispensa odbcção à rede.',
    price: 1850000.00,
    category: 'Electrodomésticos',
    subCategory: 'Cozinha',
    specificItem: 'Frigoríficos',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1584286595398-a49f783bedb5?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80'],
    stock: 4,
    minStock: 2,
    variations: [],
    rating: 4.8,
    reviewsCount: 22,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ele-002',
    name: 'Máquina de Lavar LG Vivace 9kg',
    description: 'Máquina de Lavar Roupa LG Vivace Branca com incrível capacidade de 9kg e sensor de inteligência artificial AI DD(R) que memoriza padrões. Possui tecnologia de injeção direta de vapor para eliminar bactérias.',
    price: 780000.00,
    category: 'Electrodomésticos',
    subCategory: 'Lavandaria',
    specificItem: 'Máquinas de Lavar Roupa',
    brand: 'LG',
    images: ['https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=800&q=80'],
    stock: 7,
    minStock: 2,
    variations: [],
    rating: 4.6,
    reviewsCount: 41,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // SEGURANÇA
  {
    id: 'seg-001',
    name: 'Kit de Câmaras Hikvision 4K 8CH',
    description: 'Kit completo Profissional Hikvision. Inclui 8 Câmaras 4K à prova de água (IP67) e visão noturna excecional DarkFighter. Inclui Gravador de 8 Canais NVR com deteção inteligente AI de humanos e veículos para reduzir falsos alarmes.',
    price: 650000.00,
    category: 'Segurança',
    subCategory: 'Vigilância (CCTV)',
    specificItem: 'Kits Completos',
    brand: 'Hikvision',
    images: ['https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1557597774-9d2739f85a94?auto=format&fit=crop&w=800&q=80'],
    stock: 10,
    minStock: 2,
    variations: [],
    rating: 4.7,
    reviewsCount: 35,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'seg-002',
    name: 'Fechadura Inteligente Samsung D728',
    description: 'Fechadura Inteligente Samsung D728. A solução de entrada premium. Permite abertura usando impressão biométrica ultra rápida, smartphone via Bluetooth, Cartão RFID e Teclado Numérico protegido por tecnologia antifurto.',
    price: 350000.00,
    category: 'Segurança',
    subCategory: 'Controlo de Acessos',
    specificItem: 'Fechaduras Eletrónicas',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1558222218-b7b54eede3f3?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1610486665780-69bc2fa77c8e?auto=format&fit=crop&w=800&q=80'],
    stock: 15,
    minStock: 5,
    variations: [],
    rating: 4.9,
    reviewsCount: 18,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-ms-004',
    name: 'Microsoft Entra ID P2 (Azure AD) | Anual',
    description: 'Microsoft Entra ID P2, o antigo Azure AD Premium 2. Solução completa para corporações: gestão de identidades, controlo de acessos condicional com inteligência artificial, e proteção reforçada contras identidades comprometidas em todo o mundo. Licença anual por utilizador.',
    price: 188980.51,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Cloud & Servidores',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80'],
    stock: 100,
    minStock: 5,
    variations: [],
    rating: 4.9,
    reviewsCount: 2,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-ms-005',
    name: 'Subscrição Anual Microsoft Planner e Project Plano 3',
    description: 'Subscrição Anual Microsoft Planner e Project Plano 3. Agilidade total na gestão de projetos profissionais na nuvem. Agende, trace roteiros gráficos pormenorizados e promova colaboração otimizada para todas as equipas num só lado.',
    price: 574329.84,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Cloud & Servidores',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80'],
    stock: 50,
    minStock: 5,
    variations: [],
    rating: 4.8,
    reviewsCount: 3,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-ms-006',
    name: 'Licença Microsoft Visio LTSC Standard 2021',
    description: 'Licença única Microsoft Visio LTSC Standard 2021. Ferramenta lendária para criação de organogramas, diagramas profissionais, plantas de layout de escritórios e elaboração de fluxogramas altamente detalhados, com dezenas de formas predefinidas.',
    price: 524829.25,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Outras Licenças',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80'],
    stock: 15,
    minStock: 2,
    variations: [],
    rating: 4.7,
    reviewsCount: 5,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-ms-007',
    name: 'Licença Microsoft SQL Server 2022 Enterprise Core 2',
    description: 'A joia da coroa para administradores bases de dados. Licença do Microsoft SQL Server 2022 Enterprise Edition para 2 Cores. Performance em tempo real de elite, integração bidireccional ao Azure e alta disponibilidade ininterrupta.',
    price: 4723459.90,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Cloud & Servidores',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80'],
    stock: 2,
    minStock: 1,
    variations: [],
    rating: 5.0,
    reviewsCount: 1,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'soft-ms-008',
    name: 'Subscrição Microsoft 365 E3 (no Teams) - Anual',
    description: 'Subscrição empresarial do Microsoft 365 E3 por um ano (excluindo Teams da Europa). Combina as melhores apps de produtividade, incluindo pacotes instaláveis no desktop, juntamente com incríveis recursos globais e ferramentas robustas para segurança corporativa e conformidade.',
    price: 523145.50,
    category: 'Informática',
    subCategory: 'Licenças de Software',
    specificItem: 'Cloud & Servidores',
    brand: 'Microsoft',
    images: ['https://images.unsplash.com/photo-1633419461186-7d40a38105ec?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80'],
    stock: 80,
    minStock: 10,
    variations: [],
    rating: 4.9,
    reviewsCount: 6,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // TELEMÓVEIS
  {
    id: 'pho-001',
    name: 'iPhone 15 Pro Max 256GB',
    description: 'O mais arrojado de sempre: iPhone 15 Pro Max 256GB. Construção revolucionária e super leve em Titânio de classe aeroespacial. Novo processador A17 Pro concebido para gaming de consola, porta multifacetada USB-C e câmara versátil periscópica com o novo Action Button personalizável.',
    price: 1550000.00,
    category: 'Telemóveis',
    subCategory: 'Smartphones',
    specificItem: 'iPhone (iOS)',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1695048133140-1a26b2b73bc0?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1628102491629-778571d893a3?auto=format&fit=crop&w=800&q=80'],
    stock: 20,
    minStock: 3,
    variations: [],
    rating: 4.9,
    reviewsCount: 310,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pho-002',
    name: 'Samsung Galaxy S24 Ultra 512GB',
    description: 'Samsung Galaxy S24 Ultra 512GB com chassis de Titânio resistente. O expoente máximo com inteligência artificial nativa Galaxy AI impressionante de tradução e edição. Apresenta o mais brilhante e liso ecrã plano de 6.8 Polegadas, e S-Pen inclusa para um nível superior de anotações e arte.',
    price: 1250000.00,
    category: 'Telemóveis',
    subCategory: 'Smartphones',
    specificItem: 'Samsung (Android)',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1707577533831-2917719602ff?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1605236453806-6ff368528e51?auto=format&fit=crop&w=800&q=80'],
    stock: 18,
    minStock: 3,
    variations: [],
    rating: 4.8,
    reviewsCount: 145,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // ENERGIA
  {
    id: 'ene-001',
    name: 'Painel Solar Canadian Solar 450W',
    description: 'Painel Solar de altíssima eficiência, Canadian Solar HiKu6 Mono PERC 450W. Células de potência máxima em baixa luminosidade da manhã e fim da tarde, apresentando excelente resistência mecânica aos ventos e chuvas. Ideal para sistemas domésticos de injecção ou isolados.',
    price: 110000.00,
    category: 'Energia',
    subCategory: 'Energia Solar',
    specificItem: 'Painéis Solares',
    brand: 'Canadian Solar',
    images: ['https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=800&q=80'],
    stock: 50,
    minStock: 10,
    variations: [],
    rating: 4.9,
    reviewsCount: 42,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ene-002',
    name: 'Bateria de Lítio Pylontech 3.5kWh',
    description: 'Bateria de Lítio (LiFePo4) da renomada marca Pylontech modelo US3000C, debitando eficazmente uns notáveis 3.5kWh e compatível em rack. Permite expansão modular paralela simplificada para construir potentes sistemas domésticos duráveis superiores aos de ácido.',
    price: 950000.00,
    category: 'Energia',
    subCategory: 'Energia Solar',
    specificItem: 'Baterias de Lítio',
    brand: 'Pylontech',
    images: ['https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80'],
    stock: 12,
    minStock: 2,
    variations: [],
    rating: 4.8,
    reviewsCount: 15,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // IMAGEM E SOM
  {
    id: 'ims-001',
    name: 'Smart TV Samsung 65" Neo QLED',
    description: 'Smart TV Samsung gigantesca modelo 65 polegadas Neo QLED 4K premium com matriz inovadora Quantum Matrix Technology Pro de retro-iluminação Mini LED para pretos soberbos e cores vibrantes, fluidez fenomenal a 144Hz ideal para jogos com design Infinity One ultra fino e Object Tracking Sound para som espelho direcional 3D.',
    price: 1750000.00,
    category: 'Imagem e Som',
    subCategory: 'Televisores',
    specificItem: 'OLED/QLED',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80'],
    stock: 6,
    minStock: 2,
    variations: [],
    rating: 4.7,
    reviewsCount: 38,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ims-002',
    name: 'Colunas Marshall Emberton II',
    description: 'Elegante Coluna Bluetooth estéreo da mítica marca Marshall Emberton II. Formato perfeitamente compacto envolto nos clássicos motivos premium granulados do rock n roll analógicos, mas que bombeia 30 horas incríveis de som de alta nitidez multidioreccional para viagens em ar livre e churrascos.',
    price: 145000.00,
    category: 'Imagem e Som',
    subCategory: 'Áudio Profissional',
    specificItem: 'Colunas Bluetooth',
    brand: 'Marshall',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
    stock: 30,
    minStock: 5,
    variations: [],
    rating: 4.9,
    reviewsCount: 95,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // JOGOS, CONSOLAS E DESPORTO
  {
    id: 'jog-001',
    name: 'PlayStation 5 Slim 1TB',
    description: 'Incrível entretenimento. Finalmente pode desfrutar da redesenhada e aligeirada PlayStation 5 (Modelo Slim). Inclui unidade leitor de discos 4K Bluray. Gráficos sensoriais 4K a 120 FPS incomparavelmente fotorealistas graças também ao carregamento instantâneo via SSD de 1TB mágico. Possui o revolucionário comando háptico DualSense e som tempestadual em 3D.',
    price: 780990.00,
    category: 'Jogos, Consolas e Desporto',
    subCategory: 'Consolas',
    specificItem: 'PlayStation 5',
    brand: 'Sony',
    images: ['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?auto=format&fit=crop&w=800&q=80'],
    stock: 15,
    minStock: 3,
    variations: [],
    rating: 4.9,
    reviewsCount: 150,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'jog-002',
    name: 'Nintendo Switch OLED',
    description: 'Bela consola híbrida versátil Nintendo Switch agora no adorável modelo OLED. Destaque natural do belíssimo modelo são as cores luminosas do grande novo ecrã 7 polegadas OLED, colunas revistas para áudio robusto num form factor idêntico ideal aos exclusivos amados do Mário e Zelda no seu sofá ou autocarro e com mais de 9 horas de autonomia.',
    price: 345000.00,
    category: 'Jogos, Consolas e Desporto',
    subCategory: 'Consolas',
    specificItem: 'Nintendo Switch',
    brand: 'Nintendo',
    images: ['https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1612404730960-5c71577fca11?auto=format&fit=crop&w=800&q=80'],
    stock: 22,
    minStock: 5,
    variations: [],
    rating: 4.8,
    reviewsCount: 74,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // BELEZA E SAÚDE
  {
    id: 'bel-001',
    name: 'Secador Dyson Supersonic HD15',
    description: 'Potentíssimo revolucionário Secador de mãos e Cabelo Dyson Supersonic versao HD15 em belo tom cobreado. O famoso forte motor magnético esconde-se sãos e salvas da pá para controlo perfeitamente equilibrado do ar sem escaldar danificar. Incrivelmente rápido mas incrivelmente suave em cinco configurações silenciosas sem danificação magnética na raiz do cabelo num ícone premium instantâneo.',
    price: 385000.00,
    category: 'Beleza e Saúde',
    subCategory: 'Cuidado Pessoal',
    specificItem: 'Secadores de Cabelo',
    brand: 'Dyson',
    images: ['https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80'],
    stock: 10,
    minStock: 2,
    variations: [],
    rating: 4.9,
    reviewsCount: 62,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bel-002',
    name: 'Medidor de Tensão Omron M3',
    description: 'Confiável fiável Monitor Médico preciso aparelho Medidor de Tensão arterial Omron de braço confortável super automático de categoria modelo M3 M-Intelli. Detetor automático ultra sensitivo na identificacao crua inicial de batimentos cardíacos pulsação irregulares em clínica ou repouso domiciliario permitindo historial e dupla memória.',
    price: 85000.00,
    category: 'Beleza e Saúde',
    subCategory: 'Saúde e Bem Estar',
    specificItem: 'Medidores de Tensão',
    brand: 'Omron',
    images: ['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=800&q=80'],
    stock: 45,
    minStock: 10,
    variations: [],
    rating: 4.8,
    reviewsCount: 110,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // --- NOVOS PRODUTOS ---
  {
    id: 'pc-001',
    name: 'Desktop HP Victus 15L Gaming',
    description: 'Desktop HP Victus 15L prateado. Uma silenciosa formidável torre de design elegante não chamativo mas poderosa torre interior armada ferozmente com chip super eficaz processador i7-13700F de 16 núcleos, generosos 32 GB e o potente placa de video NVidia RTX 4060 capaz de ray-tracing para que corra qualquer triplo aaa na perfeição.',
    price: 1250890.00,
    category: 'Informática',
    subCategory: 'Computadores Desktops',
    brand: 'HP',
    images: ['https://images.unsplash.com/photo-1587202372744-b0a1caadeed5?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=800&q=80'],
    stock: 8,
    minStock: 1,
    variations: [],
    rating: 4.7,
    reviewsCount: 12,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pc-002',
    name: 'MacBook Air M3 13"',
    description: 'Fino como navalha, o portátil emblemático intemporal clássico MacBook Air atualiza-se no super veloz silício chip M3 octa-core na edição mágica meia noite Midnight. Com formosa estrutura em alumínio o de ecrã vívido inigualável 13 Polegadas espetacular 500 nits, com inacreditáveis ​​inúmeros dezesoite horas de pura bateria e sem ruidosa ou enervante e inestética ventoinha ativa.',
    price: 3350000.00,
    category: 'Informática',
    subCategory: 'Computadores Portáteis',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80'],
    stock: 15,
    minStock: 2,
    variations: [],
    rating: 4.9,
    reviewsCount: 30,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'elect-001',
    name: 'Frigorífico Samsung Bespoke AI',
    description: 'Imponente elegante lindo frigorifico Samsung Bespoke AI personalizado. Sistema modular modular que personaliza painéis maravilhosos. Ele conta incrivel inteligência de arrefecimento para poupar muita eletricidade enquanto esfria precisamente no centro com metal interno refrigentário e o exclusivo centro de bebidas de acesso rápido diário na perfeiçãp sem gelo visível.',
    price: 850000.00,
    category: 'Electrodomésticos',
    subCategory: 'Cozinha',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1584286595398-a49f783bedb5?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=800&q=80'],
    stock: 5,
    minStock: 1,
    variations: [],
    rating: 4.6,
    reviewsCount: 10,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'elect-002',
    name: 'Ar Condicionado LG Artcool Dual Inverter',
    description: 'Majestoso super minimalista e silencioso sofisticado Aparelho Sistema Ar Condicionado negro em vidro preto temperado espelhado modelo LG Artcool da capacidade fantástica forte veloz inteligente em Dual Inverter incrivelmente potente no frescor purificando de forma constante sem gastar demais com uma super eficácia ecológica com app para telemóveis.',
    price: 450000.00,
    category: 'Electrodomésticos',
    subCategory: 'Climatização',
    brand: 'LG',
    images: ['https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80'],
    stock: 20,
    minStock: 3,
    variations: [],
    rating: 4.8,
    reviewsCount: 22,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'smart-001',
    name: 'iPhone 15 Pro Max 256GB',
    description: 'O mais arrojado de sempre: iPhone 15 Pro Max 256GB. Construção revolucionária e super leve em Titânio de classe aeroespacial. Novo processador A17 Pro concebido para gaming de consola, porta multifacetada USB-C e câmara versátil periscópica.',
    price: 1650000.00,
    category: 'Telemóveis',
    subCategory: 'Smartphones',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1695048133140-1a26b2b73bc0?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1628102491629-778571d893a3?auto=format&fit=crop&w=800&q=80'],
    stock: 10,
    minStock: 2,
    variations: [],
    rating: 4.9,
    reviewsCount: 50,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'smart-002',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Samsung Galaxy S24 Ultra 512GB com chassis de Titânio resistente. O expoente máximo com inteligência artificial nativa Galaxy AI impressionante de tradução e edição ecrã plano fantástico munido do inconfundível stylus de eleição focado em notas ativas.',
    price: 1100000.00,
    category: 'Telemóveis',
    subCategory: 'Smartphones',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1707577533831-2917719602ff?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1605236453806-6ff368528e51?auto=format&fit=crop&w=800&q=80'],
    stock: 12,
    minStock: 2,
    variations: [],
    rating: 4.8,
    reviewsCount: 35,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sec-001',
    name: 'Kit CCTV Dahua 8 Câmaras 4K',
    description: 'Kit completo Profissional Hikvision. Inclui 8 Câmaras 4K à prova de água (IP67) e visão noturna excecional DarkFighter. NVR inteligente IA avançado.',
    price: 485000.00,
    category: 'Segurança',
    subCategory: 'Vigilância (CCTV)',
    brand: 'Dahua',
    images: ['https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1557597774-9d2739f85a94?auto=format&fit=crop&w=800&q=80'],
    stock: 6,
    minStock: 1,
    variations: [],
    rating: 4.7,
    reviewsCount: 15,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ener-001',
    name: 'Kit Solar 5.5KVA Growatt',
    description: 'Inversor potente majestoso super silencioso eficiente Off-Grid Growatt SPF 5.5KVA 5000es moderno apto ideal perfeito gerador puro para sustentar independentemente cargas exigentes residencias com enorme precisao controlada perfeitamente no modulo Wifi e baterias conectada lítio modernas e confiável.',
    price: 2450000.00,
    category: 'Energia',
    subCategory: 'Energia Solar',
    brand: 'Growatt',
    images: ['https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=800&q=80'],
    stock: 4,
    minStock: 1,
    variations: [],
    rating: 4.9,
    reviewsCount: 8,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'game-001',
    name: 'PlayStation 5 Slim 1TB Digital',
    description: 'Elegante consola PlayStation 5 edição inteiramente Digital focada completamente perfeita para a sua bilblioteca inteira virtualizada (sem leitor discos), incrivel carregamento sem tempos de espera graças incrivel mágico ultra rapido drive SSD, som imersivo Tempest, comandos super interativos inovadores espetaculares para jogos soberbos em resoluçao em estonteante HDR.',
    price: 850000.00,
    category: 'Jogos, Consolas e Desporto',
    subCategory: 'Consolas',
    brand: 'Sony',
    images: ['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?auto=format&fit=crop&w=800&q=80'],
    stock: 12,
    minStock: 2,
    variations: [],
    rating: 4.9,
    reviewsCount: 42,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // OFFICE
  {
    id: 'off-001',
    name: 'Cadeira Gaming Alpha Gamer Vega',
    description: 'Absolutamente majestosamente confortável de Cadeira Alpha Gamer Vega ultra durável feita revestida coberta toda numa sintética suave bonita de costuras agressivas gaming fortes, assentos confortáveis largos e encosto ergonómico costas maravilhosas, descanso pés impecavel multi adjustes com o suporte formidável de ate 150Kg.',
    price: 385000.00,
    category: 'Escritório',
    subCategory: 'Mobiliário',
    brand: 'Alpha Gamer',
    images: ['https://images.unsplash.com/photo-1598550476439-6847785fce68?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&w=800&q=80'],
    stock: 5,
    minStock: 1,
    variations: [],
    rating: 4.8,
    reviewsCount: 15,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // ENERGY
  {
    id: 'ener-002',
    name: 'Bateria Lítio Pylontech US3000C',
    description: 'Bateria de Lítio (LiFePo4) Pylontech modelo US3000C, 3.5kWh compatível em rack. Permite expansão modular paralela simplificada para construir potentes sistemas domésticos duráveis sem os malefícios e cuidados extras perigosos de tradicionais chumbo ou acido convencionais antigas.',
    price: 1150000.00,
    category: 'Energia',
    subCategory: 'Energia Solar',
    brand: 'Pylontech',
    images: ['https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80'],
    stock: 10,
    minStock: 2,
    variations: [],
    rating: 4.9,
    reviewsCount: 5,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // SECURITY
  {
    id: 'sec-002',
    name: 'Câmara IP Exterior Reolink 4K',
    description: 'Câmara de segurança majestosamente IP independente Exterior autrárquica sem necessidade sem fios Reolink 4K Ultra nitidez em bateria alimentada contínuamente sol perfeitamente por pequeno prático mini lindo painel solar inteligente 100 porcento independente livre fios sem hub, conectável perfeitamente em 4G, vigiando quintas imensas com zoom motorizado impressionante em noturno a cor.',
    price: 385000.00,
    category: 'Segurança',
    subCategory: 'Vigilância (CCTV)',
    brand: 'Reolink',
    images: ['https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1557597774-9d2739f85a94?auto=format&fit=crop&w=800&q=80'],
    stock: 25,
    minStock: 5,
    variations: [],
    rating: 4.7,
    reviewsCount: 20,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  // SOUND
  {
    id: 'aud-001',
    name: 'Auscultadores Sony WH-1000XM5',
    description: 'Imponentes sofisticados auscultadores modelo premium majestoso auscultador luxo Sony WH-1000XM5 ultra levez e confortável sobre a orelha. Os inquestionáveis reis absolutos da perfeição cancelamento som ambiente externo para viagens longas nos céus ruidosos transportes ou concentração num estúdio. Som ávida dinâmico superior bluetooth ultra hi-res sem falhas emparelhado múltiplo formidável cristal claro e maravilhosos até trinta ininterruptas horas contínuas duração longa uso intenso.',
    price: 285000.00,
    category: 'Imagem e Som',
    subCategory: 'Som',
    brand: 'Sony',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80'],
    stock: 15,
    minStock: 2,
    variations: [],
    rating: 4.9,
    reviewsCount: 38,
    featured: true,
    createdAt: new Date().toISOString(),
  }
];
